### ISSUE TITLE
Is this superseded by sap-preconfigure?

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/sap-base-settings#5]
Hi,
https://github.com/linux-system-roles/sap-hana-preconfigure/blob/master/README.md states to use this for rhel7 instead of sap-preconfigure but sap-preconfigure does support rhel7 since https://github.com/linux-system-roles/sap-preconfigure/commit/abe48d4b880324711b846407d6dea31cf03127f3

**Comment by rhmk** [comment]
sap-preconfigure will replace sap-base-settings.

Klaas Demter <notifications@github.com> schrieb am Di., 15. Okt. 2019,
08:35:
